### ISSUE TITLE
Xavante dependencie error

### ISSUE THREAD

**Issue by xspager** [uluadist/lua-pkg-dev#1]
It shoud be possible to use a later version of luasocket to build Xavante http://ulua.io/luarocks_autobuild.html#xavante, is there a way to fix it? Can I help somehow?

**Comment by stepelu** [comment]
Well, the cleanest solution would be to have the rockspec author release a
new rockspec that depends on luasocket 3.0-rc2 (instead of the non-existing
2.1) and have it uploaded to luarocks.org.

Would you be able to help with that (contact relevant person / submit an
issue) ?

Failing this I can manually modify the rockspec.

**Comment by xspager** [comment]
Opened an issue on the Xavante keplerproject/xavante#19

**Comment by stepelu** [comment]
For the time being I manually modified the rockspecs for copas and xavante to use luasocket 3.0rc1.

Xavante is now available and uses copas 1.2 and luasocket 3.0rc1, hopefully that's what it needs (without agreement on versioning semantic, who knows).
